project:
  type: website

website:
  title: "Spotify Dashboard"
  favicon: images/logo.png
  page-navigation: true
  site-url: https://melissavanbussel.github.io/spotify-dashboard
  repo-url: https://github.com/melissavanbussel/spotify-dashboard
  repo-actions: [edit, source, issue]
  sidebar:
    title: "Posit 2024 Table Contest"
    style: "docked"
    search: true
    collapse-level: 1
    logo: images/logo.png
    contents: 
      - href: index.qmd
        text: Home
      - href: dashboard.qmd
        text: My entry
      - href: tutorial.qmd
        text: Tutorial
      - href: about.qmd
        text: About Me

format:
  html:
    theme: [cosmo, custom.scss]
    highlight-style: atom-one-dark
    toc: true
    grid:
      sidebar-width: 150px